/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_u2IwLjkdm",
        "userPoolWebClientId": "83r8dsr4fn4pk55fr48jr43ds",
        "oauth": {
            "domain": "us-east-2u2iwljkdm.auth.us-east-2.amazoncognito.com",
            "scope": [
                "openid",
                "email",
                "profile"
            ],
            "redirectSignIn": [
                "http://localhost:3000/"
            ],
            "redirectSignOut": [
                "http://localhost:3000/"
            ],
            "responseType": "code"
        }
    }
};


export default awsmobile;
